---
services:
  dozzle-agent:
    container_name: offsite-dozzle-agent
    image: amir20/dozzle:latest
    command: agent
    networks:
      - devrack
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${SERVER_IP}:7007:7007
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui='http://[IP]:[PORT:7070]/'
      - net.unraid.docker.icon='https://cdn.jsdelivr.net/gh/selfhst/icons/png/dozzle.png'

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
