---
services:
  wikijs_db:
    image: postgres:11-alpine
    container_name: wikijs_db
    networks:
      - devrack
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/docs/wikijs_db/:/var/lib/postgresql/data

  wikijs:
    image: ghcr.io/requarks/wiki:2
    container_name: wikijs
    networks:
      - devrack
    depends_on:
      - wikijs_db
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DB_TYPE: postgres
      DB_HOST: wikijs_db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "${SERVER_IP}:3256:3000"

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: True
