---
version: '3'
services:
  mariadb:
    container_name: nextcloud_db
    image: lscr.io/linuxserver/mariadb:latest
    networks:
      - devrack
    env_file:
      - ../server.env
      - ./cloud.env
    ports:
      - "${SERVER_IP}:3306:${MARIADB_PORT}"
    volumes:
      - /mnt/user/appdata/cloud/mariadb/config:/config
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      TZ: 'America/Chicago'
    # MYSQL_DATABASE=USER_DB_NAME #optional
    # MYSQL_USER=MYSQL_USER #optional
    # MYSQL_PASSWORD=DATABASE_PASSWORD #optional
    restart: unless-stopped

  nextcloud:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    depends_on:
      - mariadb
    networks:
      - devrack
    ports:
      - 444:444 # Changing port causes issues.
    volumes:
      - /mnt/user/NextCloud/:/data # stores all NextCloud instance data (to array)
      - /mnt/user/appdata/cloud/nextcloud/config:/config
      - /mnt/user/Adam:/data/alexandria/Adam # local Adam mount
      - /mnt/user/backups:/data/alexandria/backups # local backups mount
    environment:
      TZ: 'America/Chicago'
      PUID: 99
      PGID: 100
    restart: unless-stopped

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true